const fish = [
  "Rainbow Trout",
  "Largemouth Bass",
  "Cutthroat Trout",
  "Channel Catfish",
  "Bluegill",
  "Brook Trout",
  "Brown Trout",
  "Arctic Greyling",
  "Black Crappie",
  "Common Carp",
  "Green Sunfish",
  "Kokanee Salmon",
  "Northern Pike",
  "Smallmouth Bass",
  "Splake",
  "Tiger Trout",
  "Tiger Muskie",
  "Utah Chub",
  "Walleye",
  "Wiper",
  "Yellow Perch",
];

const fishing_spots_counties = {
  "Strawberry Reservoir": "Wasatch County",
  "Flaming Gorge Reservoir": "Daggett County",
  "Utah Lake": "Utah County",
  "Green River": "Emery County",
  "Bear Lake": "Rich County",
  "Jordanelle Reservoir": "Wasatch County",
  "Fish Lake": "Sevier County",
  "Provo River": ["Utah County", "Summit County", "Wasatch County"],
  "Lake Powell": ["San Juan County", "Kane County", "Garfield County"],
  "Bear River": [
    "Summit County",
    "Rich County",
    "Cache County",
    "Box Elder County",
  ],
  "Weber River": ["Summit County", "Morgan County", "Weber County"],
  "Deer Creek Reservoir": "Wasatch County",
  "Yuba Reservoir": ["Juab County", "Sanpete County"],
  "Starvation Reservoir": "Duchesne County",
  "East Canyon Reservoir": ["Morgan County", "Summit County"],
  "Pineview Reservoir": "Weber County",
  "Henrys Fork": "Duchesne County",
  "Lower Provo River": "Utah County",
  "Willard Bay Reservoir": ["Box Elder County", "Weber County"],
  "Mill Hollow Reservoir": ["Wasatch County", "Duchesne County"],
  "Mirror Lake": "Summit County",
  "Huntington Reservoir": "Emery County",
  "Strawberry River": "Wasatch County",
  "Sand Hollow Reservoir": "Washington County",
  "Steinaker Reservoir": "Uintah County",
  "Huntington Creek": "Emery County",
  "Electric Lake": "Carbon County",
  "Scofield Reservoir": "Carbon County",
  "Fremont River": ["Wayne County", "Garfield County"],
  "Bountiful Lake": "Davis County",
  "Rockport Reservoir": "Summit County",
  "Lake Mary": "Salt Lake County",
  "Fish Creek": "Duchesne County",
  "East Fork Sevier River": "Sevier County",
  "Little Dell Reservoir": "Salt Lake County",
  "Flaming Gorge Dam": "Daggett County",
  "Duchesne River": "Duchesne County",
  "Panguitch Lake": "Garfield County",
  "Mammoth Creek": "Garfield County",
  "Johnson Valley Reservoir": "Iron County",
  "Currant Creek Reservoir": ["Wasatch County", "Duchesne County"],
  "Echo Reservoir": "Summit County",
  "Lower Fish Creek": "Duchesne County",
  "Minersville Reservoir": "Beaver County",
  "Lake Canyon": "Emery County",
  "Blue Lake": "Duchesne County",
  "Red Creek Reservoir": "Sanpete County",
  "Ferron Reservoir": "Emery County",
  "Kents Lake": "Beaver County",
  "Huntington North Reservoir": "Emery County",
};
