const fish = [
  "Rainbow Trout",
  "Largemouth Bass",
  "Cutthroat Trout",
  "Channel Catfish",
  "Bluegill",
  "Brook Trout",
  "Brown Trout",
  "Arctic Greyling",
  "Black Crappie",
  "Common Carp",
  "Green Sunfish",
  "Kokanee Salmon",
  "Northern Pike",
  "Smallmouth Bass",
  "Splake",
  "Tiger Trout",
  "Tiger Muskie",
  "Utah Chub",
  "Walleye",
  "Wiper",
  "Yellow Perch",
];
